# Generated by Django 5.0.2 on 2024-02-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azureauth', '0003_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
