# Generated by Django 5.0.2 on 2024-02-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureauth', '0004_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
